// <auto-generated />
using System;
using HotelApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelApi.Models.ExtraOption", b =>
                {
                    b.Property<int>("ExtraOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("extraOptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraOptionId"));

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ExtraOptionId");

                    b.ToTable("ExtraOption", (string)null);
                });

            modelBuilder.Entity("HotelApi.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("facilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities", (string)null);
                });

            modelBuilder.Entity("HotelApi.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentInfoId")
                        .HasColumnType("int")
                        .HasColumnName("paymentInfoID");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationID");

                    b.Property<int?>("ReservationId1")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("PaymentInfoId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ReservationId1");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("HotelApi.Models.PaymentInfo", b =>
                {
                    b.Property<int>("PaymentInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentInfoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentInfoId"));

                    b.Property<string>("BankHolderName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("PaymentInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentInfo", (string)null);
                });

            modelBuilder.Entity("HotelApi.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("HotelApi.Models.ReservedExtraOption", b =>
                {
                    b.Property<int>("ExtraOptionId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("ExtraOptionId", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservedExtraOptions");
                });

            modelBuilder.Entity("HotelApi.Models.ReservedFacility", b =>
                {
                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("facilityID");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("reservationID");

                    b.HasKey("FacilityId", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservedFacilities");
                });

            modelBuilder.Entity("HotelApi.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("HotelApi.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roomTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoomTypeId");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("HotelApi.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelApi.Models.Invoice", b =>
                {
                    b.HasOne("HotelApi.Models.PaymentInfo", "PaymentInfo")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentInfoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HotelApi.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApi.Models.Reservation", null)
                        .WithMany("Invoices")
                        .HasForeignKey("ReservationId1");

                    b.Navigation("PaymentInfo");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelApi.Models.PaymentInfo", b =>
                {
                    b.HasOne("HotelApi.Models.User", "User")
                        .WithMany("PaymentInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelApi.Models.Reservation", b =>
                {
                    b.HasOne("HotelApi.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelApi.Models.ReservedExtraOption", b =>
                {
                    b.HasOne("HotelApi.Models.ExtraOption", "ExtraOption")
                        .WithMany("ReservedExtraOptions")
                        .HasForeignKey("ExtraOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelApi.Models.Reservation", "Reservation")
                        .WithMany("ReservedExtraOptions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraOption");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelApi.Models.ReservedFacility", b =>
                {
                    b.HasOne("HotelApi.Models.Facility", "Facility")
                        .WithMany("ReservedFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelApi.Models.Reservation", "Reservation")
                        .WithMany("ReservedFacilities")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelApi.Models.Room", b =>
                {
                    b.HasOne("HotelApi.Models.Reservation", "Reservation")
                        .WithMany("Rooms")
                        .HasForeignKey("ReservationId");

                    b.HasOne("HotelApi.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelApi.Models.ExtraOption", b =>
                {
                    b.Navigation("ReservedExtraOptions");
                });

            modelBuilder.Entity("HotelApi.Models.Facility", b =>
                {
                    b.Navigation("ReservedFacilities");
                });

            modelBuilder.Entity("HotelApi.Models.PaymentInfo", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("HotelApi.Models.Reservation", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("ReservedExtraOptions");

                    b.Navigation("ReservedFacilities");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelApi.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelApi.Models.User", b =>
                {
                    b.Navigation("PaymentInfos");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
